apiVersion: v2
publisher: hackajob
name: auto-commit
version: 0.0.1
type: Che Editor
displayName: Auto Commit
title: Auto Commit
description: Auto Commit
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
# repository: https://github.com/Microsoft/vscode
category: Editor
firstPublicationDate: '2019-11-29'
url: https://github.com/caciobanu/che-theia-auto-commit/raw/master/plugin.tar.gz
spec:
  containers:
  - image: eclipse/che-theia-endpoint-runtime:next
    name: hackajob-auto-commit
    memoryLimit: '256Mi'