apiVersion: v2
publisher: hackajob
name: auto_commit
version: 0.0.1
type: Theia plugin
displayName: Auto Commit
title: Auto Commit
description: Auto Commit
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
# repository: https://github.com/Microsoft/vscode
category: Editor
firstPublicationDate: '2019-11-29'
# url: https://github.com/caciobanu/che-theia-auto-commit/raw/master/auto_commit.theia
spec:
  extensions:
  - https://github.com/caciobanu/che-theia-auto-commit/raw/master/auto_commit.theia