apiVersion: v2
publisher: hackajob
name: auto-commit
version: 0.0.1
type: Eclipse Che Plugin
displayName: Auto Commit
title: Auto Commit
description: Auto Commit
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
# repository: https://github.com/Microsoft/vscode
category: Language
firstPublicationDate: '2019-11-29'
spec:
  containers:
  - image: "docker.io/eclipse/che-remote-plugin-node:next"
    name: hackajob-auto-commit
    memoryLimit: '256Mi'
  extensions:
  - https://github.com/caciobanu/che-theia-auto-commit/archive/master.zip
